#!/usr/bin/env python3
"""Build the dependency-free ``run_robinhood_standalone.py`` artifact.

The maintained source stays modular under ``copybot/``. This builder flattens
those modules in dependency order and removes only their internal imports, so
the shareable artifact cannot drift from the tested implementation.
"""

from __future__ import annotations

import ast
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "run_robinhood_standalone.py"
SOURCES = (
    ROOT / "copybot" / "decimal_utils.py",
    ROOT / "copybot" / "models.py",
    ROOT / "copybot" / "accounting.py",
    ROOT / "copybot" / "backtest.py",
    ROOT / "copybot" / "gmgn.py",
    ROOT / "copybot" / "analytics.py",
    ROOT / "copybot" / "telegram_report.py",
    ROOT / "run_robinhood.py",
)


def _is_internal_import(node: ast.stmt) -> bool:
    if not isinstance(node, ast.ImportFrom):
        return False
    if node.module == "__future__":
        return True
    return node.level > 0 or bool(node.module and node.module.startswith("copybot"))


def _flatten(path: Path) -> str:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    body: list[ast.stmt] = []
    for index, node in enumerate(tree.body):
        if index == 0 and isinstance(node, ast.Expr):
            value = node.value
            if isinstance(value, ast.Constant) and isinstance(value.value, str):
                continue
        if _is_internal_import(node):
            continue
        body.append(node)
    flattened = ast.Module(body=body, type_ignores=[])
    ast.fix_missing_locations(flattened)
    return ast.unparse(flattened)


def main() -> int:
    digest = hashlib.sha256()
    sections: list[str] = []
    for path in SOURCES:
        source = path.read_bytes()
        digest.update(path.relative_to(ROOT).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(source)
        sections.append(
            f"# ===== BEGIN {path.relative_to(ROOT).as_posix()} =====\n"
            f"{_flatten(path)}\n"
            f"# ===== END {path.relative_to(ROOT).as_posix()} ====="
        )

    header = f'''#!/usr/bin/env python3
"""Standalone Robinhood Chain copy-trading analyzer.

AUTO-GENERATED by build_standalone.py. Do not edit this artifact directly.
It contains the GMGN client, spot backtest, analytics, scoring, and multilingual
Telegram report renderer. Only Python 3.11+ and a GMGN API key are required.

Usage:
    GMGN_API_KEY=gmgn_... python3 run_robinhood_standalone.py 0xWallet zh-CN
"""

from __future__ import annotations

__standalone_source_sha256__ = "{digest.hexdigest()}"
'''
    rendered = header + "\n\n" + "\n\n".join(sections) + "\n"
    temporary = OUTPUT.with_suffix(".py.tmp")
    temporary.write_text(rendered, encoding="utf-8")
    temporary.replace(OUTPUT)
    OUTPUT.chmod(0o755)
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
